
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upquyueevqrbitmijqsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwcXV5dWVldnFyYml0bWlqcXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NzgxNDYsImV4cCI6MjA1NzU1NDE0Nn0.vniqT2Jt1ffPfarL9iXyYyYsAdBWuEH2yM8aSds0sQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Initialize the Supabase client with debugging
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});

// Log initialization
console.log('Supabase client initialized with URL:', SUPABASE_URL);

// Export a helper function to test connection
export const testConnection = async () => {
  try {
    const { data, error } = await supabase.from('clientes').select('count(*)', { count: 'exact' });
    if (error) {
      console.error('Connection test failed:', error);
      return { success: false, error };
    }
    return { success: true, data };
  } catch (err) {
    console.error('Connection test exception:', err);
    return { success: false, error: err };
  }
};
